// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFacturacion.DAL;

#nullable disable

namespace SistemaFacturacion.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241019013021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.DTE", b =>
                {
                    b.Property<Guid>("DTE_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres_service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authorization_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DTE_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DTE_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DTE_serie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DTE_type_id")
                        .HasColumnType("int");

                    b.Property<string>("Issuer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issuer_nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver_nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total_amount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DTE_Id");

                    b.HasIndex("DTE_number")
                        .IsUnique();

                    b.HasIndex("DTE_type_id");

                    b.ToTable("DTE");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.DTE_detail", b =>
                {
                    b.Property<int>("DTE_datail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DTE_datail_id"));

                    b.Property<Guid>("DTE_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Item_descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Item_number")
                        .HasColumnType("int");

                    b.Property<decimal>("Item_quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Item_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total_item_price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DTE_datail_id");

                    b.HasIndex("DTE_id");

                    b.ToTable("DTE_detail");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.DTE_type", b =>
                {
                    b.Property<int>("DTE_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DTE_type_id"));

                    b.Property<string>("DTE_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.HasKey("DTE_type_id");

                    b.ToTable("DTE_type");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.DTE", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.Entities.DTE_type", "DTE_type")
                        .WithMany()
                        .HasForeignKey("DTE_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DTE_type");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.DTE_detail", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.Entities.DTE", "DTE")
                        .WithMany("DteDetails")
                        .HasForeignKey("DTE_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DTE");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entities.DTE", b =>
                {
                    b.Navigation("DteDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
